Repository AY2223S2-CS2103T-W11-1/tp, pull requests merged in 2023-03, with the labels that each got.

#48 Add location
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/core/WingmanParser.java
  src/main/java/seedu/address/logic/location/addlocation/AddLocationCommand.java
  src/main/java/seedu/address/logic/location/addlocation/AddLocationCommandFactory.java
  src/main/java/seedu/address/logic/location/deletelocation/DeleteLocationCommand.java
  src/main/java/seedu/address/logic/location/deletelocation/DeleteLocationCommandFactory.java
  src/main/java/seedu/address/logic/pilot/deletepilot/DeletePilotCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/location/Location.java
  src/main/java/seedu/address/model/location/exceptions/DuplicateLocationException.java
  src/main/java/seedu/address/model/location/exceptions/LocationNotFoundException.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/json/adapted/JsonAdaptedLocation.java
  src/main/java/seedu/address/storage/json/serializable/JsonSerializableLocationManager.java
  src/main/java/seedu/address/storage/json/storage/JsonLocationManagerStorage.java
Labels: enhancement

#51 Fix the path of location
  src/main/java/seedu/address/model/UserPrefs.java
Labels: bug

#78 Add link/unlink location to flight
  src/main/java/seedu/address/logic/core/WingmanParser.java
  src/main/java/seedu/address/logic/location/linklocation/LinkLocationCommand.java
  src/main/java/seedu/address/logic/location/linklocation/LinkLocationCommandFactory.java
  src/main/java/seedu/address/logic/location/unlinklocation/UnlinkLocationCommand.java
  src/main/java/seedu/address/logic/location/unlinklocation/UnlinkLocationCommandFactory.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/flight/Flight.java
  src/main/java/seedu/address/model/location/Location.java
  src/main/java/seedu/address/storage/json/adapted/JsonAdaptedFlight.java
Labels: enhancement

#97 fix issue #96
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/flight/addflight/AddFlightCommandFactory.java
  src/main/java/seedu/address/model/flight/Flight.java
  src/main/java/seedu/address/model/link/Link.java
  src/main/java/seedu/address/storage/json/adapted/JsonAdaptedFlight.java
  src/main/java/seedu/address/ui/FlightListPanel.java
Labels: bug

#101 Make panel full width
  src/main/resources/view/MainWindow.fxml
Labels: enhancement

#111 Update developper guide
  docs/DeveloperGuide.md
  docs/diagrams/WingmanDeleteXYZDiagram.puml
  docs/images/WingmanDeleteXYZSequenceDiagram.png
  docs/images/WingmanUnlinkXYZSequenceDiagram.png
Labels: documentation

#105 Change UUID to index for all commands
  src/main/java/seedu/address/logic/crew/checkcrew/CheckCrewCommand.java
  src/main/java/seedu/address/logic/crew/deletecrew/DeleteCrewCommand.java
  src/main/java/seedu/address/logic/crew/linkcrew/LinkCrewCommand.java
  src/main/java/seedu/address/logic/crew/linkcrew/LinkCrewCommandFactory.java
  src/main/java/seedu/address/logic/crew/unlinkcrew/UnlinkCrewCommandFactory.java
  src/main/java/seedu/address/logic/flight/deleteflight/DeleteFlightCommand.java
  src/main/java/seedu/address/logic/location/deletelocation/DeleteLocationCommand.java
  src/main/java/seedu/address/logic/location/linklocation/LinkLocationCommandFactory.java
  src/main/java/seedu/address/logic/location/unlinklocation/UnlinkLocationCommandFactory.java
  src/main/java/seedu/address/logic/pilot/checkpilot/CheckPilotCommand.java
  src/main/java/seedu/address/logic/pilot/deletepilot/DeletePilotCommand.java
  src/main/java/seedu/address/logic/pilot/linkpilot/LinkPilotCommandFactory.java
  src/main/java/seedu/address/logic/pilot/unlinkpilot/UnlinkPilotCommandFactory.java
  src/main/java/seedu/address/logic/plane/checkplane/CheckPlaneCommand.java
  src/main/java/seedu/address/logic/plane/deleteplane/DeletePlaneCommand.java
  src/main/java/seedu/address/logic/plane/linkplane/LinkPlaneCommandFactory.java
  src/main/java/seedu/address/logic/plane/unlinkplane/UnlinkPlaneCommandFactory.java
  src/main/java/seedu/address/model/ItemManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyItemManager.java
  src/main/java/seedu/address/model/exception/IndexOutOfBoundException.java
Labels: enhancement

#135 Update user guide
  docs/UserGuide.md
  docs/images/UG-index-reference.png
Labels: documentation
